name: Discord Notify

on:
  push:
  pull_request:
  issues:
  create:
  delete:
  release:
  check_run:
  workflow_job:
  fork:
  watch:
    types: [started]
  public:
  member:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          E: ${{ github.event_name }}
          A: ${{ github.event.action }}
          R: ${{ github.repository }}
          REF: ${{ github.ref_name }}
        run: |
          set -e

          ICON="ðŸ“Œ"
          TEXT="$R"

          case "$E" in
            push)
              ICON="âœ…"
              TEXT="$R â†’ $REF"
              ;;
            pull_request)
              ICON="ðŸ”"
              TEXT="PR ${A}"
              ;;
            issues)
              ICON="ðŸ›"
              TEXT="Issue ${A}"
              ;;
            create)
              ICON="ðŸŒ±"
              TEXT="Created ${GITHUB_EVENT_REF_TYPE:-ref} ${GITHUB_EVENT_REF:-}"
              ;;
            delete)
              ICON="ðŸ§¨"
              TEXT="Deleted ${GITHUB_EVENT_REF_TYPE:-ref} ${GITHUB_EVENT_REF:-}"
              ;;
            release)
              ICON="ðŸ·ï¸"
              TEXT="Release ${A}"
              ;;
            check_run)
              ICON="ðŸ§ª"
              TEXT="Checks ${A}"
              ;;
            workflow_job)
              STATUS="${{ github.event.workflow_job.status }}"
              ICON="ðŸ¤–"
              [ "$STATUS" = "completed" ] && ICON="ðŸ¤–âœ…"
              TEXT="Workflow $STATUS"
              ;;
            fork)
              ICON="ðŸ´"
              TEXT="Forked"
              ;;
            watch)
              ICON="â­"
              TEXT="Star"
              ;;
            public)
              ICON="ðŸŒ"
              TEXT="Now public"
              ;;
            member)
              ICON="ðŸ‘¤"
              TEXT="Collaborator ${A}"
              ;;
          esac

          MSG="$ICON **$TEXT**"

          curl -sS -X POST -H "Content-Type: application/json" \
            -d "{\"content\":\"$MSG\"}" \
            "$WEBHOOK" >/dev/null
